import type { Metadata } from "next";
import "./globals.css";
import { Fredoka } from 'next/font/google'
import Navbar from '@/components/Navbar';
const fredoka = Fredoka({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fredoka.className} antialiased`}>
        <>
        <Navbar/>
        {children}
        </>
      </body>
    </html>
  );
}
